name: autodl
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.8.10
  - pytorch=1.4.0
  - torchvision
  - pip
  - tensorboardX
  - pycocotools
  - tqdm
  - numpy
  - pandas
  - nvidia-apex
  - rasterio
